config/routes.rb
Plas::Application.routes.draw do
  resources :waivers
  resources :registration_transfers
  resources :registration_gift_logs
  resources :transactions
  resources :pcfgs

  match '/events/calendar(.:format)' => 'events#calendar'
  resources :events do
    resource :address
    match '/register' => 'registrations#register', :as => :register
    match '/register/review' => 'registrations#review', :as => :registerreview
    match '/register/pay' => 'registrations#pay', :as => :registerpay
    match '/register/paypal' => 'registrations#paypal_redirect', :as => :registerpaypal
    match '/register/confirm' => 'registrations#confirm', :as => :registerconfirm
    match '/register/return' => 'registrations#return', :as => :registerreturnpay
    match '/register/success' => 'registrations#success', :as => :registersuccess
    match '/register/error' => 'registrations#error', :as => :registererror
    match '/register/reserve' => 'registrations#reserve', :as => :registerreserve
    match '/registration/:id' => 'registrations#show'
    match '/registration/:id/edit' => 'registrations#edit'
    match '/registrations' => 'registrations#index'
    match '/set_current' => 'events#set_current', :as => :setcurrent
    match '/set_waiver' => 'events#set_waiver', :as => :setwaiver
    resources :tickets
    resources :tournaments
  end
  match '/give_registration' => 'registration_gift_logs#new', :as => :givereg
  match '/give_registration' => 'registration_gift_logs#create', :as => :givereg, :via => :post

	resource :account, :controller => "users"
	
  resources :users do
    resource :address
  end

	resource :user_sessions
	match '/login' => 'user_sessions#new', :as => 'login'
	match '/logout' => 'user_sessions#destroy', :as => 'logout'
  resources :permissions
  resources :user_groups do
    match '/list_candidates' => 'user_groups#list_candidates', :as => 'list_candidates'
    match '/add_permission' => 'user_groups#add_permission', :as => 'add_permission'
    match '/remove_permission/:permission_id' => 'user_groups#remove_permission', :as => 'remove_permission'
    match '/add_user' => 'user_groups#add_user', :as => 'add_user'
    match '/remove_user/:user_id' => 'user_groups#remove_user', :as => 'remove_user'
  end
  match '/godmode' => 'user_groups#godmode', :as => 'godmode'
  root :to => "home#index"

end

app/models/user_group.rb
class UserGroup < ActiveRecord::Base
  attr_accessible :name
  #this is basically the join model for user<->permissions

  #TODO: validations
  has_many :user_to_user_group, :dependent => :destroy
  has_many :users, :through => :user_to_user_group
  has_many :permission_to_user_group, :dependent => :destroy
  has_many :permissions, :through => :permission_to_user_group

end

app/controllers/user_groups_controller.rb
class UserGroupsController < ApplicationController

=begin
######
these methods deal with adding users to a group
####
=end

  def list_candidates
    @user_group = UserGroup.find(params[:user_group_id])
    @users = User.all
    #get the list of users NOT in the group already
    @user_list = @users - @user_group.users

    respond_to do |format|
      format.html
      format.xml { render :xml => @user_list }
      format.json { render :json => @user_list }
    end
  end

  def add_permission
    @user_group = UserGroup.find(params[:user_group_id])
    @permission = Permission.find(params[:permission_to_user_groups][:permission_id])

    @user_group.permissions << @permission

    respond_to do |format|
      if @user_group.save
        format.html { redirect_to(request.referrer, :notice => _("%s added to %s") % [@permission.name, @user_group.name]) }
        format.json { render :json => true }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user_group.errors, :status => :unprocessable_entity }
      end
    end
  end

  def remove_permission
    @user_group = UserGroup.find(params[:user_group_id])
    @permission = Permission.find(params[:permission_id])

    @user_group.permissions.delete @permission
  
    respond_to do |format|
      if @user_group.save
        format.html { redirect_to(request.referrer, :notice => _("%s removed from %s.") % [@permission.name, @user_group.name]) }
        format.json { render :json => true }
        format.xml  { head :ok }
      else
        format.html { render :action => "show", :notice => _("Unable to remove permission %s from group %s") % [@permission.name, @user_group.name] }
        format.json { render :json => @user_group.errors, :status => :failure }
        format.xml  { render :xml => @user_group.errors, :status => :unprocessable_entity }
      end
    end
  end

  def add_user
    @user_group = UserGroup.find(params[:user_group_id])
    @user = User.find(params[:user_to_user_groups][:user_id])

    @user_group.users << @user

    respond_to do |format|
      if @user_group.save
        format.html { redirect_to(request.referrer, :notice => _("%s added to %s") % [@user.display_name, @user_group.name]) }
        format.json { render :json => true }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user_group.errors, :status => :unprocessable_entity }
      end
    end
  end

  def remove_user
    @user_group = UserGroup.find(params[:user_group_id])
    @user = User.find(params[:user_id])

    @user_group.users.delete @user
  
    respond_to do |format|
      if @user_group.save
        format.html { redirect_to(request.referrer, :notice => _("%s removed from %s.") % [@user.display_name, @user_group.name]) }
        format.json { render :json => true }
        format.xml  { head :ok }
      else
        format.html { render :action => "show", :notice => _("Unable to remove user %s from group %s") % [@user.display_name,@user_group.name] }
        format.json { render :json => @user_group.errors, :status => :failure }
        format.xml  { render :xml => @user_group.errors, :status => :unprocessable_entity }
      end
    end
  end

=begin
######
#This method makes someone god if there are no admins
######
=end

  def godmode
    paa = Permission.find_by_code('app.administrate')
    if paa.users.count == 0
      g = paa.user_groups[0] #get the first group which has admin
                             #permissions, usually Applications Admins
      
      g.users << current_user
      if g.save
        respond_to do |format|
          format.html { 
            redirect_to(root_path, 
                        :notice => _("You, %s, are now a part of %s, which has administrator permissions.") % [current_user.display_name, g.name]
                       ) 
          }
          format.xml { head :ok }
        end
      end
    else
      respond_to do |format|
        format.html {
          redirect_to(root_path,
                      :notice => _("You cannot play god!")
                     )
        }
        format.xml { head :error }
      end
    end
  end

=begin
######
method below here deal with the CRUD of the UserGroup itself
####
=end
  
  # GET /user_groups
  # GET /user_groups.xml
  def index
    @user_groups = UserGroup.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @user_groups }
    end
  end

  # GET /user_groups/1
  # GET /user_groups/1.xml
  def show
    @user_group = UserGroup.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user_group }
    end
  end

  # GET /user_groups/new
  # GET /user_groups/new.xml
  def new
    @user_group = UserGroup.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user_group }
    end
  end

  # GET /user_groups/1/edit
  def edit
    @user_group = UserGroup.find(params[:id])
  end

  # POST /user_groups
  # POST /user_groups.xml
  def create
    @user_group = UserGroup.new(params[:user_group])

    respond_to do |format|
      if @user_group.save
        format.html { redirect_to(@user_group, :notice => 'User group was successfully created.') }
        format.xml  { render :xml => @user_group, :status => :created, :location => @user_group }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user_group.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /user_groups/1
  # PUT /user_groups/1.xml
  def update
    @user_group = UserGroup.find(params[:id])

    respond_to do |format|
      if @user_group.update_attributes(params[:user_group])
        format.html { redirect_to(@user_group, :notice => 'User group was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user_group.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /user_groups/1
  # DELETE /user_groups/1.xml
  def destroy
    @user_group = UserGroup.find(params[:id])
    @user_group.destroy

    respond_to do |format|
      format.html { redirect_to(user_groups_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/user_groups_helper.rb
module UserGroupsHelper
end

app/views/user_groups/_form.html.erb
<%= form_for(@user_group) do |f| %>
  <% if @user_group.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@user_group.errors.count, "error") %> prohibited this user_group from being saved:</h2>
    <ul>
    <% @user_group.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_groups/_list_select.html.erb
<% if !ul or ul.count == 0 %>
  <span class="message warning">
    <%= _("There are no users who are not already in this group.")%>
  </span>
<% else %>
  <% form_for :user_to_user_groups, 
              :html => { :id => "user-groups-list-candidates"}, 
              :as => :post, 
              :url => user_group_add_user_url(ug) do |f| %>
                <%= f.select "user_id", ul.collect {|u| [u.display_name, u.id]}, {:include_blank => true } %>
                <%= f.submit %>
  <% end %>
<% end %>

app/views/user_groups/_select_permissions.html.erb
<% if !pl or pl.count == 0 %>
  <span class="message warning">
    <%= _("There are no users who are not already in this group.")%>
  </span>
<% else #TODO: make this select show the permissions grouped by category %>
  <%= form_for :permission_to_user_groups, 
              :html => { :id => "user-groups-list-permissions"}, 
              :as => :post, 
              :url => user_group_add_permission_url(ug) do |f| %>
                <%= f.select "permission_id", pl.sort{|q,w| q.sort_text(w)}.collect {|p| ["%s: %s" % [p.category, p.name], p.id]}, {:include_blank => true } %>
                <%= f.submit %>
  <% end %>
<% end %>

app/views/user_groups/_select_users.html.erb
<% if !ul or ul.count == 0 %>
  <span class="message warning">
    <%= _("There are no users who are not already in this group.")%>
  </span>
<% else %>
  <%= form_for :user_to_user_groups, 
              :html => { :id => "user-groups-list-candidates"}, 
              :as => :post, 
              :url => user_group_add_user_url(ug) do |f| %>
                <%= f.select "user_id", ul.collect {|u| [u.display_name, u.id]}, {:include_blank => true } %>
                <%= f.submit %>
  <% end %>
<% end %>

app/views/user_groups/edit.html.erb
<% title = _("Editing %s") % @user_group.name %>
<% content_for :title do %>
  <%=title %>
<% end %>

<h1><%=title %></h1>
<%= render 'form' %>

<%= link_to 'Show', @user_group %> |
<%= link_to 'Back', user_groups_path %>

app/views/user_groups/index.html.erb
<% title = _("Listing user_groups") %>
<% content_for :title do %>
  <%=title %>
<% end %>

<h1><%=title %></h1>
<table>
  <tr>
    <th>Name</th>
    <th># Permissions</th>
    <th># Members</th>
    <th></th>
    <th></th>
  </tr>

<% @user_groups.each do |user_group| %>
  <tr>
    <td><%= link_to user_group.name, user_group %></td>
    <td><%= user_group.permissions.count %></td>
    <td><%= user_group.users.count %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User group', new_user_group_path %>

app/views/user_groups/list_candidates.html.erb
<% title = _("Add a user to %s") % @user_group.name %>
<% content_for :title do %>
  <%=title %>
<% end %>

<h1><%=title %></h1>
<%= render :partial => "user_groups/select_users", :locals => { :ul => @user_list, :ug => @user_group } %>

<br/><br/>
<%= link_to _("Back to %s") % @user_group.name, @user_group %>

app/views/user_groups/new.html.erb
<% title = _("New user_group") %>
<% content_for :title do %>
  <%=title %>
<% end %>

<h1><%=title %></h1>
<%= render 'form' %>

<%= link_to 'Back', user_groups_path %>

app/views/user_groups/show.html.erb
<% title =  _("%s group") % @user_group.name %>
<% content_for :title do %>
  <%=title %>
<% end %>

<h1><%=title %></h1>
<p class="notice"><%= notice %></p>

<div id="user-group-users">
  <h2><%= _("Users for %s") % @user_group.name %></h2>
  <% if @user_group.users.count == 0 %>
    <span><%= _("There are no users in this group.") %></span>
  <% else %>
    <ul id="user-group-users-list">
      <% @user_group.users.sort{|a,b| a.display_name <=> b.display_name}.each do |user|%>
        <li class="user">
          <%= link_to user.display_name, user %>
          <% #TODO: this should be async! %>
          <%= link_to "X", user_group_remove_user_path(@user_group, :user_id => user)  %>
        </li>
      <% end %>
    </ul>
  <% end %>
  <fieldset>
    <legend><%= _("Add users to %s") % @user_group.name %></legend>
    <% #TODO: autocomplete %>
    <!--<input type="text" value="Type to find"/>-->
    <%= render :partial => "user_groups/select_users", :locals => {:ul => User.all - @user_group.users, :ug => @user_group }  %>
  </fieldset>
</div>
<hr/>
<div id="user-group-permissions">
  <h2><%= _("Permissions for %s") % @user_group.name %></h2>
  <% if @user_group.permissions.count == 0 %>
    <span><%= _("There are no permissions for this group.") %></span>
  <% else %>
    <ul id="user-group-permissions-list">
      <% @user_group.permissions.each do |perm|%>
        <li class="permission">
          <%= perm.name %>
          <% #TODO: this should be async! %>
          <%= link_to "X", user_group_remove_permission_path(@user_group, :permission_id => perm)  %>
        </li>
      <% end %>
    </ul>
  <% end %>
  <fieldset>
    <legend><%= _("Add permissions to %s") % @user_group.name %></legend>
    <% #TODO: autocomplete %>
    <!--<input type="text" value="Type to find"/>-->
    <input type="text" value="Type to find"/>
    <%= render :partial => "user_groups/select_permissions", :locals => {:pl => Permission.all - @user_group.permissions, :ug => @user_group }  %>
  </fieldset>
</div>
<div id="admin-tools">
<%= link_to _("Edit %s") % @user_group.name, edit_user_group_path(@user_group) %> |
<%= link_to _("Destroy %s") % @user_group.name, @user_group, :confirm => _('Are you sure? This cannot be undone and you may regret it.'), :method => :delete %>
</div>
<%= link_to 'Back', user_groups_path %>