config/routes.rb
Plas::Application.routes.draw do
  resources :waivers
  resources :registration_transfers
  resources :registration_gift_logs
  resources :transactions
  resources :pcfgs

  match '/events/calendar(.:format)' => 'events#calendar'
  resources :events do
    resource :address
    match '/register' => 'registrations#register', :as => :register
    match '/register/review' => 'registrations#review', :as => :registerreview
    match '/register/pay' => 'registrations#pay', :as => :registerpay
    match '/register/paypal' => 'registrations#paypal_redirect', :as => :registerpaypal
    match '/register/confirm' => 'registrations#confirm', :as => :registerconfirm
    match '/register/return' => 'registrations#return', :as => :registerreturnpay
    match '/register/success' => 'registrations#success', :as => :registersuccess
    match '/register/error' => 'registrations#error', :as => :registererror
    match '/register/reserve' => 'registrations#reserve', :as => :registerreserve
    match '/registration/:id' => 'registrations#show'
    match '/registration/:id/edit' => 'registrations#edit'
    match '/registrations' => 'registrations#index'
    match '/set_current' => 'events#set_current', :as => :setcurrent
    match '/set_waiver' => 'events#set_waiver', :as => :setwaiver
    resources :tickets
    resources :tournaments
  end
  match '/give_registration' => 'registration_gift_logs#new', :as => :givereg
  match '/give_registration' => 'registration_gift_logs#create', :as => :givereg, :via => :post

	resource :account, :controller => "users"
	
  resources :users do
    resource :address
  end

	resource :user_sessions
	match '/login' => 'user_sessions#new', :as => 'login'
	match '/logout' => 'user_sessions#destroy', :as => 'logout'
  resources :permissions
  resources :user_groups do
    match '/list_candidates' => 'user_groups#list_candidates', :as => 'list_candidates'
    match '/add_permission' => 'user_groups#add_permission', :as => 'add_permission'
    match '/remove_permission/:permission_id' => 'user_groups#remove_permission', :as => 'remove_permission'
    match '/add_user' => 'user_groups#add_user', :as => 'add_user'
    match '/remove_user/:user_id' => 'user_groups#remove_user', :as => 'remove_user'
  end
  match '/godmode' => 'user_groups#godmode', :as => 'godmode'
  root :to => "home#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  #things we'll access regularly
  attr_accessible :name, :pronunciation, :handle, :email, :birthdate, :gender,
                  :disabled, :password
  #mostly internal things that are OK to access for admins only
  attr_accessible :created_at, :updated_at, :login_count, :failed_login_count, 
                  :last_request_at, :current_login_at, :last_login_at, 
                  :current_login_ip, :last_login_ip

  validates :name, :presence => true, 
                   :length => { :minimum => 1 }

  validates :pronunciation, :presence => true, 
                            :length => { :minimum => 1 }

	validates :email, :presence => true,  
			              :format => { 
                      :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i 
                     }

	has_many :addresses, :dependent => :destroy

  has_many :user_to_user_group
  has_many :user_groups, :through => :user_to_user_group
  has_many :registrations
  
  has_and_belongs_to_many :tournaments
  
  #TODO: make this work and get rid of #permissions and #build_permissions
  #has_many :permissions, :through => :user_groups, :source => :user_groups

	acts_as_authentic do |c|
		c.require_password_confirmation = false
	end
	
  def self.find_one_by_handle(handle)
		@l = find(:all, :conditions => ["LOWER(handle) = ?", handle.downcase])
		if @l.length > 1
			@l
		else
			@l[0]
		end
	end
	def self.find_by_handle(handle)
		find(:all, :conditions => ["LOWER(handle) = ?", handle.downcase])
	end

  def build_permissions
    #ideally, this would be handled by the has_many :permissions, but that
    #doesn't work no matter what I try
    #
    #TODO: improve efficiency of this giant thing
    groups = self.user_groups
    perms = groups.collect do |g|
      g.permissions.collect do |p|
        [p, p.descendants]
      end
    end
    perms.flatten.uniq
  end
  private :build_permissions

  def permissions
    #we only should calculate this once, because it's expensive
    @permissions ||= build_permissions
  end

	def can(permission_code)
		#TODO: Implement some kind of cache, as it's likely that the same
    #permission will hit more than once is a page load, no sense in going
    #through all of the permissions again every time.
    if permissions.select {|p| p.code == permission_code }.count != 0
      return true
    else
      if Rails.env.development? and not Permission.find_by_code(permission_code)
        raise _("Permission code %s does not exist") % permission_code
      end
    end
    false
	end

	def has_handle
		return (handle and not handle.empty?)
	end

	def display_name
		return handle if has_handle
    return name
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_no_user, :only => [:new, :create]
  before_filter :require_user, :only => [:show, :edit, :update, :destroy ]
  
  def is_user_current_or_admin?(user) 
    user == current_user or current_user.can('users.administrate')   
  end
  # GET /users
  # GET /users.xml
  def index
    @users = User.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end
  
  # GET /users/1
  # GET /users/1.xml
  def show
    if params[:id]
      @user = User.find_by_id(params[:id])
    else
      @user = current_user
    end

    #there's gotta be a better way to do this in the view
    @is_user_current_or_admin = is_user_current_or_admin? @user

    @unpaid_registrations = Registration.unpaid_for(@user) if current_user.can('payments.accept')

    #this gets ones they bought, which isn't in @user.registrations
    @my_registrations = Registration.where( "user_id = ? OR (user_id = NULL AND purchaser_id = ?)", @user, @user ).limit(10)

    
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end
  
  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end
  
  # GET /users/1/edit
  def edit
    @u = params[:id] ? User.find(params[:id]) : current_user
    if is_user_current_or_admin?(@u)
      @user = current_user
    else
      flash[:notice] = _("You aren't permitted to change this user")
      render :action => :show
    end
  end
  
  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])
    
    respond_to do |format|
      if @user.save
        format.html { 
          redirect_to(account_url, :notice => _('Your account was successfully created.')) 
        }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  # PUT /users/1
  # PUT /users/1.xml
  def update
    @u = User.find(params[:id])
    if is_user_current_or_admin? @u
      @user = current_user
    else
      redirect_to(account_url, :notice => _("You do not have permission to update %s") % @u.display_name)
      return
    end
    
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(account_url, :notice => _('Your account was successfully updated.')) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    if is_user_current_or_admin? @user
      @user.destroy
    else
      redirect_to(account_url, :notice => _("You do not have permission to destroy %s") % @user.display_name)
      return
    end
    
    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit_form.html.erb
  <% if @user.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

<dl class="user-info form-list">
  <fieldset>
    <legend><%= _('Edit User Information') %></legend>

    <dt><%= f.label :name %></dt>
    <dd><%= f.text_field :name %></dd>

    <dt><%= f.label :pronunciation %></dt>
    <dd><%= f.text_field :pronunciation %></dd>

    <dt><%= f.label :handle %></dt>
    <dd><%= f.text_field :handle %></dd>

    <dt><%= f.label :email %></dt>
    <dd><%= f.email_field :email, {:required => true, :pattern => "[^ @]*@[^ @]*\.[^@]*", :placeholder => _("Your email address") }%></dd>
 

    <dt><%= f.label :password, f.object.new_record? ? nil : _("Change password") %></dt>
    <dd><%= f.password_field :password %></dd>

    <dt><%= f.label :birthdate %></dt>
    <dd><%= f.date_select :birthdate, :start_year => Time.now.year - 100, 
																	:end_year => Time.now.year - 13,
																	:default => Time.now - 18.years %></dd>

	<dt>&nbsp;</dt>
    <dd style="height: 4em;"><%= _('If you are younger than this date, you may need your parents\' signature on the waiver to enter the event. No exceptions are granted to this rule.') %></dd>

    <dt><%= f.label :gender %></dt>
    <dd><%= f.text_field :gender %></dd>

   <dt><%= f.label :disabled %></dt>
   <dd><%= f.check_box :disabled %> <%= _("Checking this will disable your account. You will be able to login, but others will not be able to see your profile and will not be able to otherwise interact with you other than remove you from tournaments and such.") %></dd>
  </fieldset>
</dl>

app/views/users/_form.html.erb
  <% if @user.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= f.label :given_name %>
    <%= f.text_field :given_name %>
		<br/>
    <%= f.label :family_name %>
    <%= f.text_field :family_name %>
  </div>
  <div class="field">
    <%= f.label :handle %><br />
    <%= f.text_field :handle %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password, f.object.new_record? ? nil : "Change password" %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :gaming_group %><br />
    <%= f.text_field :gaming_group %>
  </div>
  <div class="field">
    <%= f.label :date_arrival %><br />
    <%= f.datetime_select :date_arrival %>
  </div>
  <div class="field">
    <%= f.label :date_departure %><br />
    <%= f.datetime_select :date_departure %>
  </div>
  <div class="field">
    <%= f.label :gamer_type %><br />
<% #TODO: i18n and put into User %>
    <%= f.select :gamer_type, %w[computer console both] %>

  </div>
  <div class="field">
    <%= f.label :birthdate %><br />
    <%= f.date_select :birthdate, :start_year => Time.now.year - 100, 
																	:end_year => Time.now.year - 13,
																	:default => Time.now - 18.years %>
		<%= _('If you are younger than this date, you may need your parents\' signature on the waiver to enter the event. No exceptions are granted to this rule.') %>
  </div>
  <div class="field">
    <%= f.label :gender %><br />
<% #TODO: i18n and put into User %>
    <%= f.select :gender, %w[male female hermaphrodite transsexual pansexual adventurous], :include_blank => _('Prefer not to answer') %>
  </div>

app/views/users/_new_user_form.html.erb
  <% if @user.errors.any? %>
  <div id="errorExplanation">
    <h2>
			<%= 
			_('%s prevented you from joining our ranks:') % pluralize(@user.errors.count, "error") 
			%>
		</h2>
    <ol>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ol>
  </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :handle %>
    <%= f.text_field :handle %>
  </div>

  <div class="field">
    <%= f.label :pronunciation %>
    <%= f.text_field :pronunciation %>
  </div>
  <div class="field">
    <%= f.label :birthdate %>
    <%= f.date_select :birthdate,
                        {
                        :start_year => Time.now.year - 100, 
                        :end_year => Time.now.year - 13, 
                        :default => Time.now - 18.years,
                        } %>
    <span class="note">
		  <%= _('If you are younger than this date, you may need your parents\' signature on the waiver to enter the event. No exceptions are granted to this rule.') %>
  </span>
  </div>
  <div class="field">
    <%= f.label :gender %>
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :password, f.object.new_record? ? nil : "Change password" %>
    <%= f.password_field :password %>
  </div>

app/views/users/_tools.html.erb
<% if @user == current_user or current_user.can('users.administrate') %>
<section id="user-admin-tools" class="admin-tools">
	<header>
		<h1><%= _('Adminster %s') % @user.handle  %></h1>
	</header>
	<ul>
		<li><%= link_to(_('Edit %s') % @user.handle , edit_user_path(@user), :class => 'icon edit') %></li>
		<li><%= link_to(_('Delete %s') % @user.handle, user_path(@user), :confirm => _('Are you sure you want to delete %s? This could destroy some referential integrity and cripple the application. It is better to disable the user.') % @user.handle, :method => :delete, :class => 'icon delete' ) %></li>
	</ul>
</section>
<% end %>

app/views/users/edit.html.erb
<% title =  _('Edit User %s') % @user.display_name %>
<% content_for :title do %>
  <%=title %>
<% end %>

<h1><%=title %></h1>

<%=form_for @user, :url => user_path(@user) do |f| %>
	<%= f.error_messages %>
	<%= render :partial => "edit_form", :locals => { :f => f } %>
    <div class="submit-options">
	  <%= f.submit _('Save changes') %> or <%= link_to _('Cancel'), @user %>
    </div>
<% end %>

app/views/users/index.html.erb
<% title =  _('Listing users') %>
<% content_for :title do %>
  <%=title %>
<% end %>

<h1><%=title %></h1>
<% if @users.count == 0 %>
  <p class="message">
    <%= _("There are no registered users in this system.") %>
  </p>
<% else %>
  <ul id="user-list">
    <% @users.each do |user| %>
      <li><%= link_to user.display_name, user %> </li>
    <% end %>
  </ul>
<% end %>

app/views/users/new.html.erb
<% title =  _('Register') %>
<% content_for :title do %>
  <%=title %>
<% end %>

<h1><%=title %></h1>
<%= form_for @user, :url => account_url do |f| %>
	<%= render :partial => "new_user_form", :locals => { :f => f } %>
	<%= f.submit _('Register') %>
<% end %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<% title =  _('Show User') %>
<% content_for :title do %>
  <%=title %>
<% end %>

<h1><%=title %></h1>

<dl class="user-info info-list">
  <fieldset>
    <legend><%= _('User Information') %></legend>
    <%=render :partial => 'users/tools'%>

    <dt><%= _('Name') %></dt>
    <dd><%= @user.name %></dd>
    
    <dt><%= _('Handle') %></dt>
    <dd><%= ( @user.handle and not @user.handle.empty? ) ? @user.handle : _('%s has not set a handle.') % @user.display_name %></dd>

    <dt><%= _('Pronunciation') %></dt>
    <dd><%= ( @user.pronunciation and not @user.pronunciation.empty? ) ? @user.pronunciation : _('%s has not set a pronunciation.') % @user.display_name %></dd>
    
    <dt><%= _('Email') %></dt>
    <dd><%= @user.email %></dd>
    
    <dt><%= _('Birthdate') %></dt>
    <dd><%= @user.birthdate %></dd>
    
    <dt><%= _('Gender') %></dt>
    <dd><%= @user.gender %></dd>
  
    <dt><%= _('Created') %></dt>
    <dd><%= @user.created_at %></dd>
  </fieldset>

  <% if current_user.can('payments.accept') %>
  <fieldset>
    <legend><%= _('Unpaid registrations') %></legend>
    <% if @unpaid_registrations.count > 0 %>
      <%= form_for Transaction.new, :url => new_transaction_url, :html => {:method => 'get'}  do |f| %>
          <%= select :registrations, :ids, @unpaid_registrations.collect{|reg| [("%s - %s - %s %s" % [
            reg.ticket.event.name,
            reg.ticket.name,
            reg.price_paid.currency.symbol,
            reg.price_paid]), reg.to_param]}, {}, {:multiple => true}
          %>
            <%= f.submit _("Record payments") %>
        <% end %>
    <% else %>
      <span><%= _("%s has no unpaid registrations.") % @user.display_name %></span>
    <% end %>
  </fieldset>
  <% end %>

  <% if @is_user_current_or_admin %>
    <fieldset>
      <legend><%= @user == current_user ? _("My Registrations") : _("%s's Registrations") % @user.display_name %></legend>
      <% if @my_registrations.count > 0 %>
        <ul>
          <% @my_registrations.each do |reg| %>
            <li>
              <%= ("%s - %s - %s %s" % [
              reg.ticket.event.name,
              reg.ticket.name,
              reg.price_paid.currency.symbol,
              reg.price_paid]) %>
              
              <% if reg.paid? %>
                <%= _("Paid") %> 
              <% else %>
                <%= _("Awaiting offline payment") %>
              <% end %>

              <% if reg.givable? and (reg.givable_by == current_user or current_user.can("registrations.transfer")) %>
                <%= link_to _("Transfer?"), new_registration_transfer_url(:registration => reg)   %>
              <% elsif reg.checked_in? %>
                <%= _("Checked in at %s") % reg.date_checked_in %>
              <% end %>

              <% if reg.given? %>
                <%= (_("Given to %s on %s") % [
                     link_to(reg.user.display_name, reg.user), 
                     reg.date_given]) %>
              <% end %>

              <%= link_to _("Print waiver"), waiver_url(reg.ticket.event.waiver) if reg.ticket.event.waiver %>


            </li>
          <% end %>
        </ul>
      <% else %>
        <p><%= @user == current_user ? _("You have no registrations.") : _("%s has no registrations.") % @user.display_name %></p>
      <% end %>
    </fieldset>
  <% end %>

  <% if current_user.can('users.administrate') %>
  <fieldset>
    <legend><%= _('Internals') %></legend>
    <dt><%= _('Last updated') %></dt>
    <dd><%= @user.updated_at %></dd>

    <dt><%= _('Disabled?') %></dt>
    <dd><%= @user.disabled %></dd>
    
    <dt><%= _('Login count') %></dt>
    <dd><%= @user.login_count %></dd>
    
    <dt><%= _('Last request at') %></dt>
    <dd><%= @user.last_request_at %></dd>
    
    <dt><%= _('Last login at') %></dt>
    <dd><%= @user.last_login_at %></dd>
    
    <dt><%= _('Current login at') %></dt>
    <dd><%= @user.current_login_at %></dd>
    
    <dt><%= _('Last login ip') %></dt>
    <dd><%= @user.last_login_ip %></dd>
    
    <dt><%= _('Current login ip') %></dt>
    <dd><%= @user.current_login_ip %></dd>
  </fieldset>
<% end %>
</dl>