config/routes.rb
Plas::Application.routes.draw do
  resources :waivers
  resources :registration_transfers
  resources :registration_gift_logs
  resources :transactions
  resources :pcfgs

  match '/events/calendar(.:format)' => 'events#calendar'
  resources :events do
    resource :address
    match '/register' => 'registrations#register', :as => :register
    match '/register/review' => 'registrations#review', :as => :registerreview
    match '/register/pay' => 'registrations#pay', :as => :registerpay
    match '/register/paypal' => 'registrations#paypal_redirect', :as => :registerpaypal
    match '/register/confirm' => 'registrations#confirm', :as => :registerconfirm
    match '/register/return' => 'registrations#return', :as => :registerreturnpay
    match '/register/success' => 'registrations#success', :as => :registersuccess
    match '/register/error' => 'registrations#error', :as => :registererror
    match '/register/reserve' => 'registrations#reserve', :as => :registerreserve
    match '/registration/:id' => 'registrations#show'
    match '/registration/:id/edit' => 'registrations#edit'
    match '/registrations' => 'registrations#index'
    match '/set_current' => 'events#set_current', :as => :setcurrent
    match '/set_waiver' => 'events#set_waiver', :as => :setwaiver
    resources :tickets
    resources :tournaments
  end
  match '/give_registration' => 'registration_gift_logs#new', :as => :givereg
  match '/give_registration' => 'registration_gift_logs#create', :as => :givereg, :via => :post

	resource :account, :controller => "users"
	
  resources :users do
    resource :address
  end

	resource :user_sessions
	match '/login' => 'user_sessions#new', :as => 'login'
	match '/logout' => 'user_sessions#destroy', :as => 'logout'
  resources :permissions
  resources :user_groups do
    match '/list_candidates' => 'user_groups#list_candidates', :as => 'list_candidates'
    match '/add_permission' => 'user_groups#add_permission', :as => 'add_permission'
    match '/remove_permission/:permission_id' => 'user_groups#remove_permission', :as => 'remove_permission'
    match '/add_user' => 'user_groups#add_user', :as => 'add_user'
    match '/remove_user/:user_id' => 'user_groups#remove_user', :as => 'remove_user'
  end
  match '/godmode' => 'user_groups#godmode', :as => 'godmode'
  root :to => "home#index"

end

app/models/event.rb
class Event < ActiveRecord::Base
  #attr_accessible :address_attributes
  attr_accessible :name, :start, :end, :description
  attr_accessible :registration_open, :visible
  has_many :addresses, :dependent => :destroy
  has_many :tickets, :dependent => :destroy
  has_many :tournaments, :dependent => :destroy
  belongs_to :waiver

  accepts_nested_attributes_for :addresses, :allow_destroy => true
  #TODO: validations

  def find_available_tickets
    tickets.select {|t| t.available?}
  end

  def seats_available
    num_seats_available = 0
    tickets.each do |t|
      num_seats_available = num_seats_available + t.available
    end
    num_seats_available
  end
  def seats_remaining
    num_seats_remaining = 0
    tickets.each do |t|
      num_seats_remaining = num_seats_remaining + t.remaining
    end
    num_seats_remaining
  end
  def calculate_num_seats
    tickets.each do |t|
      @num_seats_available = @num_seats_available + t.available
      @num_seats_remaining = @num_seats_remaning + t.remaining
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_filter :require_permission_events_administrate, :only => [:new, :create, :edit, :update, :destroy, :set_current, :set_waiver]
  # GET /events
  # GET /events.xml
  def index
    @events = Event.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @events }
      format.ics
    end
  end

  def calendar
    @events = Event.all
    @calendar = Icalendar::Calendar.new
    @events.each do |e|
      @calendar.event do
        dtstart e.start
        dtend e.end
        summary e.name
        klass "PRIVATE"
      end
    end
    @calendar.publish

    respond_to do |format|
      format.ics { render :text => @calendar.to_ical }
    end
  end

  # GET /events/1
  # GET /events/1.xml
  def show
    begin
      @event = Event.find(params[:id])
      @waivers = Waiver.all if current_user and current_user.can('events.administrate')
      respond_to do |format|
        format.html # show.html.erb
        format.xml  { render :xml => @event }
      end
    rescue ActiveRecord::RecordNotFound
      redirect_to events_path
    end
  end

  # GET /events/new
  # GET /events/new.xml
  def new
    @event = Event.new
    @event.addresses.build if @event.addresses.length == 0
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.xml
  def create
    @event = Event.new(params[:event])

		respond_to do |format|
      if @event.save
        format.html { redirect_to(@event, :notice => _('Event was successfully created.')) }
        format.xml  { render :xml => @event, :status => :created, :location => @event }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.xml
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to(@event, :notice => _('Event was successfully updated.')) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.xml
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to(events_url) }
      format.xml  { head :ok }
    end
  end

  def set_current
    if Event.find(params[:event_id])
      Pcfg.set('event.current',params[:event_id], current_user)
    end
    redirect_to request.referrer
  end

  def set_waiver
    event = Event.find(params[:event_id])
    begin
      waiver = Waiver.find(params[:event][:waiver_id])
    rescue ActiveRecord::RecordNotFound
      waiver = nil
    end

    if event
      event.waiver = waiver
      respond_to do |format|
        if event.save
          format.html do
            if waiver.nil?
              notice = _("Waiver removed from %{event_name}") % {:event_name => event.name}
            else
              notice = _("Waiver %{title} set as the active waiver for %{event_name}") % { :title => waiver.title, :event_name => event.name }
            end
            redirect_to event, :notice => notice 
          end
          format.xml { head :ok }
        else
          format.html { render :action => "show" }
          format.xml { render :xml => @event.errors, :status => :unprocessable_entity }
        end
      end
    end
    return
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <dl class="event-info form-list">
    <fieldset>
      <legend><%= _('Event Information') %></legend>
      <dt><%= f.label :name %></dt>
      <dd><%= f.text_field :name %></dd>

      <dt><%= f.label :start %></dt>
      <dd><%= f.datetime_select :start %></dd>

      <dt><%= f.label :end %></dt>
      <dd><%= f.datetime_select :end %></dd>

      <dt><%= f.label :description %></dt>
      <dd><%= f.text_area :description %></dd>
    </fieldset>

    <fieldset>
      <legend><%= _('Address') %></legend>
    <%= f.fields_for :addresses do |af| %>
      <dt><%= af.label :line1 %></dt>
	  <dd><%= af.text_field :line1 %></dd>

	  <dt><%= af.label :line2 %></dt>
	  <dd><%= af.text_field :line2 %></dd>

	  <dt><%= af.label :line3 %></dt>
	  <dd><%= af.text_field :line3 %></dd>

	  <dt><%= af.label :neighborhood %></dt>
      <dd><%= af.text_field :neighborhood %></dd>

	  <dt><%= af.label :city %></dt>
      <dd><%= af.text_field :city %></dd>

	  <dt><%= af.label :region %></dt>
      <dd><%= af.text_field :region %></dd>

	  <dt><%= af.label :country %></dt>
      <dd><%= af.text_field :country %></dd>

	  <dt><%= af.label :postcode %></dt>
      <dd><%= af.text_field :postcode %></dd>

	  <dt><%= af.label :phone %></dt>
    <dd><%= af.telephone_field :phone, { :pattern => '^\(?\d{3}\)?[-\s]?\d{3}[-\s]?\d{4}.*?$' } %></dd>

      <dt><%= af.label :address_type %></dt>
      <dd><%= af.select :address_type, Address::TYPES, :default => "event" %></dd>

	  <%= af.hidden_field :primary, :value => true %>
    <% end %>
    </fieldset>

    <fieldset>
      <legend><%= _('Options') %></legend>
      <dt><%= f.label :registration_open %></dt>
      <dd><%= f.check_box :registration_open %></dd>

      <dt><%= f.label :visible %></dt>
      <dd><%= f.check_box :visible, :checked_value => 1, :unchecked_value => 0, :checked => true%></dd>
    </fieldset>
  </dl>

app/views/events/_ticket_tools.html.erb
<% if current_user and current_user.can 'events.administrate' %>
  <section id="event-admin-tools" class="admin-tools">
    <ul>
      <li><%= link_to _('Create a ticket'), new_event_ticket_path(@event), :class => 'icon create-ticket' %></li>
    </ul>
  </section>
<% end %>

app/views/events/_tools.html.erb
<% if current_user and current_user.can 'events.administrate' %>
  <section id="event-admin-tools" class="admin-tools">
    <ul>
      <li><%= link_to _('Edit'), edit_event_path(@event), :class => 'icon edit' %></li>
      <li><%= link_to _('Delete'), @event, :confirm => 'Are you sure?', :method => :delete, :class => 'icon delete' %></li>
      <li><%= (current_event == @event) ? _("Current event") : link_to(_("Set current"), event_setcurrent_path(@event)) %></li>
      <li>
        <%= form_tag event_setwaiver_path(@event), :remote => true do -%>
          Waiver:
          <%= select :event, 'waiver_id', @waivers.collect {|w| [w.title, w.id]}, {:include_blank => true, :remote=>true}, {:onChange => 'this.parentNode.submit()'} %>
        <% end %>
    </ul>
  </section>
<% end %>

app/views/events/edit.html.erb
<% title = _('Editing Event') %>
<% content_for :title do %>
  <%=title %>
<% end %>

<h1><%=title %></h1>

<%= form_for @event do |f| %>
  <%= f.error_messages %>
  <%= render :partial => "form", :locals => { :f => f } %>
  <div class="submit-options">
    <%= f.submit %> or <%= link_to 'Back', event_path(@event) %>
  </div>
<% end %>

app/views/events/index.html.erb
<% title = _('Listing Events') %>
<% content_for :title do %>
  <%=title %>
<% end %>

<h1><%=title %></h1>

<% if @events.count == 0 %>
  <p class="message">
    <%= _("There are no events scheduled.") %>
  </p>
<% end %>

<% @events.each do |event| %>
  <% if event.visible or (current_user and current_user.can 'events.administrate') %>
  <article class="event">
    <h1><%= link_to event.name, event %></h1>
    <h2><%= event.description %></h2>
    <p><%= event.start.to_date %> - <%= event.end.to_date %></p>
    <p><%= event.addresses[0].pretty if event.addresses.count > 0 %></p>
    <p><%=
      if event.registration_open
        _("Registration is open")
      else
        _("Registration is closed")
      end%></p>
    <% if current_user and current_user.can 'events.administrate' %>
      <div class="available-tickets">
        <% if event.tickets.count > 0 %>
          <h3>Available tickets</h3>
        <ul>
          <% event.tickets.each do |ticket| %>
            <li><%= ticket.name %> - 
               $<%= ticket.price %> - 
               <%= _('%d tickets available') % ticket.available %>, 
               <%= _('%d tickets remaining') % ticket.remaining %>
            </li>
          <% end %>
        </ul>
        <% end %>
      </div>
      <div class="admin-actions">
        <%= link_to 'Edit', edit_event_path(event) %> 
        <%= link_to 'Destroy', event, :confirm => 'Are you sure?', :method => :delete %>
        <%= (current_event == event) ? _("Current event") : link_to(_("Set current"), event_setcurrent_path(event)) %>
      </div>
    <% end %>
  </article>
  <% end %>

<% end %>

<br />

<%= link_to 'New Event', new_event_path if current_user and current_user.can 'events.create' %>

app/views/events/new.html.erb
<% title = _('New Event') %>
<% content_for :title do %>
  <%=title %>
<% end %>

<h1><%=title %></h1>

<%= form_for @event do |f| %>
  <%= f.error_messages %>
  <%= render :partial => "form", :locals => { :f => f } %>
  <div class="submit-options">
    <%= f.submit %> or <%= link_to 'Back', events_path %>
  </div>
<% end %>

app/views/events/show.html.erb
<% title = _('Show Event') %>
<% content_for :title do %>
  <%=title %>
<% end %>

<h1><%=title %></h1>

<% if notice and not notice.empty? %><p class="notice"><%= notice %></p><%end%>

<dl class="event-info info-list">
  <fieldset>
    <legend>Event Information</legend>
    <%=render :partial => 'events/tools'%>

    <dt><%= _('Name') %></dt>
    <dd><%= @event.name %></dd>

    <dt>Start</dt>
    <dd><%= @event.start %></dd>

    <dt>End</dt>
    <dd><%= @event.end %></dd>

    <dt>Description</dt>
    <dd><%= @event.description %></dd>
  </fieldset>

  <fieldset>
    <legend><%= _('Address') %></legend>

  <% @event.addresses.each do |address| %>
    <dt>Address</dt>
    <dd><%= address.pretty %></dd>
  <% end %>
  </fieldset>
  <% if current_user and current_user.can 'events.administrate' %>
  <fieldset>
    <legend><%= _('Options') %></legend>

    <dt>Registration Open</dt>
    <dd><%= @event.registration_open %></dd>

    <dt>Visible</dt>
    <dd><%= @event.visible %></dd>
  </fieldset>
  <%end%>
</dl>

<dl class="event-tickets info-list">
  <fieldset>
    <legend><%= _('Tickets') %></legend>
    <%=render :partial => 'events/ticket_tools'%>
    <% if @event.tickets.count == 0 %>
      <p><i><%= _('No tickets have been created for this event. No seats are available.') %></i></p>
    <% else %>
    <p><%= _("There are %d seats remaining of %d seats available for this event.") % [@event.seats_remaining, @event.seats_available] %></p>


    <% @event.tickets.each do |t| %>
      <dt class="<%= t.available? ? "available" : "unavailable" %>">
        <%=t.name%> 
        <% if current_user and current_user.can('events.administrate') %>
          [<%= link_to _("e"), event_ticket_path(@event, t) %>]
        <% end %>
      </dt>
      <dd class="<%= t.available? ? "available" : "unavailable" %>">
        <%= "%s %s" % [t.price.currency.symbol, t.price] %>
        <%=
          if t.available?
            _("%d tickets available, %d tickets remaining") % [t.available, t.remaining]
          else
            if t.sold_out?
              _("This ticket is sold out.")
            else
              _("This ticket is no longer available.")
            end
          end
        %>

      </dd>
    <% end %>
    <div class="ticket-actions">
      <%= link_to _("Purchase tickets for this event"), event_register_path(@event) if @event.registration_open %><br/>
      <%= link_to _("Who is registered?"), event_registrations_url(@event) %>
    </div>
<% end %>
  </fieldset>
</dl>

<%= link_to 'Back', events_path %>