config/routes.rb
Plas::Application.routes.draw do
  resources :waivers
  resources :registration_transfers
  resources :registration_gift_logs
  resources :transactions
  resources :pcfgs

  match '/events/calendar(.:format)' => 'events#calendar'
  resources :events do
    resource :address
    match '/register' => 'registrations#register', :as => :register
    match '/register/review' => 'registrations#review', :as => :registerreview
    match '/register/pay' => 'registrations#pay', :as => :registerpay
    match '/register/paypal' => 'registrations#paypal_redirect', :as => :registerpaypal
    match '/register/confirm' => 'registrations#confirm', :as => :registerconfirm
    match '/register/return' => 'registrations#return', :as => :registerreturnpay
    match '/register/success' => 'registrations#success', :as => :registersuccess
    match '/register/error' => 'registrations#error', :as => :registererror
    match '/register/reserve' => 'registrations#reserve', :as => :registerreserve
    match '/registration/:id' => 'registrations#show'
    match '/registration/:id/edit' => 'registrations#edit'
    match '/registrations' => 'registrations#index'
    match '/set_current' => 'events#set_current', :as => :setcurrent
    match '/set_waiver' => 'events#set_waiver', :as => :setwaiver
    resources :tickets
    resources :tournaments
  end
  match '/give_registration' => 'registration_gift_logs#new', :as => :givereg
  match '/give_registration' => 'registration_gift_logs#create', :as => :givereg, :via => :post

	resource :account, :controller => "users"
	
  resources :users do
    resource :address
  end

	resource :user_sessions
	match '/login' => 'user_sessions#new', :as => 'login'
	match '/logout' => 'user_sessions#destroy', :as => 'logout'
  resources :permissions
  resources :user_groups do
    match '/list_candidates' => 'user_groups#list_candidates', :as => 'list_candidates'
    match '/add_permission' => 'user_groups#add_permission', :as => 'add_permission'
    match '/remove_permission/:permission_id' => 'user_groups#remove_permission', :as => 'remove_permission'
    match '/add_user' => 'user_groups#add_user', :as => 'add_user'
    match '/remove_user/:user_id' => 'user_groups#remove_user', :as => 'remove_user'
  end
  match '/godmode' => 'user_groups#godmode', :as => 'godmode'
  root :to => "home#index"

end

app/views/layouts/_footer.html.erb
<section id="footer">
<div id="clear-footer">
<br class="clear-footer"/>
</div>
<footer>
<% if current_user and current_user.can('app.administrate') %>
<nav id="admin-links" class="inline">
<ul>
<li><%= link_to _("Transactions"), transactions_path %></li>
<li><%= link_to _("Pcfgs"), pcfgs_path %></li>
<li><%= link_to _("Permissions"), permissions_path %></li>
<li><%= link_to _("User Groups"), user_groups_path %></li>
<li><%= link_to _("Registration Transfers"), registration_transfers_path %></li>
<li><%= link_to _("Waivers"), waivers_path %></li>
</ul>
</nav>
<% end %>
<% if current_user and Permission.find_by_code('app.administrate').users.count == 0 
#TODO: find a better place for this 
%>
<div id="become-god">
  <%= _('There is currently no administrator.') %>
  <%= link_to _("Become administrator?"), godmode_path %>
</div>
<% end %>
<div id="copyright-notice">
  <p>
    <span class="project">
      <a href="<%= Plas::PROJECT_URL %>"><acronym title="<%= _('Pittco LAN Administration System') %>">PLAS</acronym></a>
    </span>
    <span class="version">
      v<%= Plas::VERSION %>
    </span>
    &copy; 
    <span class="company">
      <a href="http://www.pittco.org">Pittsburgh LAN Coalition, Inc.</a>
    </span>
  </p>
</div>
</footer>
</section>

app/views/layouts/_guest_user.html.erb
<ul class="guest-user">
  <li id="current-time"><%= Time.now.strftime("%Y-%m-%d %H:%M:%S") %></li>
  <li><%= link_to _("Users"), users_path %></li>
  <li><%= link_to _("Events"), events_path %></li>
  <li><%= link_to _('Sign up'), new_user_path %></li>
  <li><%= link_to _('Login'), login_path %></li>
</ul>

app/views/layouts/_header.html.erb
<head>
  <title><%= Pcfg.get('organization.name') || _("Pittco") %> :: <%=yield :title %></title>    
  <%= stylesheet_link_tag "reset","structure","color" %>
  <%= javascript_include_tag ['jquery.min', 'jquery-ui.min','rails','date'] %>
  <%= javascript_include_tag ['application'] %>
  <%= csrf_meta_tag %>
  <link rel="icon" type="image/vnd.microsoft.icon" href="/images/logos/plas/plas_logo.ico"/>
  <link rel="apple-touch-icon" href="/images/logos/plas/plas_logo.ico">
</head>

app/views/layouts/_masthead.html.erb
<section id="header">
<nav id="global" class="inline">
<%=
if current_user
	render :partial => "layouts/registered_user"
else
	render :partial => "layouts/guest_user"
end
%>
</nav>
<header>
<h1><%= Pcfg.get('organization.name') || _("Pittco") %></h1>
<h2 title="v<%= Plas::VERSION %>">
  <%= Pcfg.get('organization.app_name') || _("Pittco LAN Administration System") %>
</h2>
</header>
<nav id="event-modules" class="inline">
<%=
if current_event
  render :partial => "layouts/nav_current_event"
else
  render :partial => "layouts/nav_no_event"
end
%>
</nav>
</section>

app/views/layouts/_nav_current_event.html.erb
<ul>
    <li class="event-name"><%= current_event.name %>
    <ul>
      <li>
        <%= link_to _("Dashboard"), root_path %>
      </li>
      <li>
        <%= link_to _("Tournaments"), event_tournaments_path(current_event) %>
      </li>
      <li>
        <%= link_to _("Seating Map"), root_path %>
      </li>
    </ul>
  </li>
</ul>

app/views/layouts/_nav_no_event.html.erb
<ul>
  <li>
    <%= link_to _("Home"), root_path %>
  </li>
</ul>

app/views/layouts/_notices.html.erb
<% if alert and not alert.empty? %>
  <p class="notice alert">
    <%= alert %>
  </p>
<% end %>
<% if notice and not notice.empty? %>
  <p class="notice">
    <%= notice %>
  </p>
<% end %>

app/views/layouts/_registered_user.html.erb
<ul class="registered-user">
	<li id="current-time"><%= Time.now.strftime("%Y-%m-%d %H:%M:%S") %></li>
  <li><%= link_to _("Users"), users_path %></li>
  <li><%= link_to _("Events"), events_path %></li>
	<li><%= link_to current_user.display_name, account_url %></li>
	<li><%= link_to _('Logout'), logout_path %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<%= render :partial => "layouts/header" %>
<body>
<%= render :partial => "layouts/masthead" %>
<section id="content">
<%= render :partial => "layouts/notices" %>
<%= yield %>
</section>
<%= render :partial => "layouts/footer" %>
</body>
</html>